name:                clickeasy
version:             0.1.0.0
homepage:            https://github.com/hecke-rs/clickeasy#readme
license:             BSD3
author:              Erin Moon
maintainer:          erin@hashbang.sh
copyright:           2018 Erin Moon
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - wai-extra
  - http-types
  - blaze-html
  - hedis
  - hashids
  - text
  - bytestring
  - transformers

executables:
  clickeasy:
    source-dirs:      src
    main:             Main.hs
